spring:
  application:
    name: security
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: spring
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  security:
    user:
      name: admin
      password: 1234
      # roles:  ADMIN
    oauth2:
      client:
        registration:
          kakao:
            client-id:  4d3bccf60a93b84ba29ec50d734a3204
            client-secret:  LlVKzUAXan1pJLAxCNpoU6c7dGmzJO20
            client-name: kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.naver.com
    port: 465
    username: jjang051@naver.com
    password: 8N8XPNDKJUFW
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable:  true
            trust:  smtp.naver.com
        debug:  true


  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  mapper-locations:  classpath:/mapper/**/*.xml
  type-aliases-package: com.jjang051.security.member.dto,com.jjang051.security.board.dto
  configuration:
    map-underscore-to-camel-case: true